### ISSUE TITLE
The `acts_as_token_authenticatable` method gets missing when using v1.9.0 with Mongoid

### ISSUE THREAD

**Issue by vumanhcuongit** [gonzalo-bulnes/simple_token_authentication#168] opened 2015-04-26 13:00 UTC
I had upgraded my Rails application to 4.2.0 then I got an error when starting my application:
```
`<class:User>': undefined local variable or method `acts_as_token_authenticatable' for User:Class (NameError)
```

I define the method in model User as below:
```
acts_as_token_authenticatable
field :authentication_token, type: String
```
I'm using devise (3.4.1), simple_token_authentication (1.9.0) and mongoid for database.

Could you help me the case ?

**Comment by gonzalo-bulnes** [comment] 2015-04-26 16:13
Hello @vumanhcuongit,

I really don't think that's a Rails support issue (Rails 4 is fully supported). You are using Mongoid, can you please check that you're including `Mongoid::Document` in your model? (Eventually, can you post a bit more of your model here?)

I think it may be a loading order issue, similar to (but not exactly the same as) [this one][1].

Let me explain you briefly how the loading works, so that you can help me finding where the issue comes from:

  1. When the app is started, the gems code is required in an order which is first determined by Bundler from their dependency relations, then by the order in which they appear in the `Gemfile`.
Simple Token Authentication does **not** depend on Mongoid, and that's why #158 was failing. However, you are not getting a `NoAdapterAvailableError`, so that doesn't seem to be the cause of your issue.
  2. When Mongoid is present, _Simple Token Authentication_ does load an adapter which task consists in extending `Mongoid::Document` with the `acts_as_token_authenticatable` method. That's why you **must** include `Mongoid::Document` in you model to get access to the  `acts_as_token_authenticatable` method.
If you did, the first thing I would check is that the `acts_as_token_authenticatable` method call in your model contains no misspelling. (It may happen!) Can you check that please? 

Keep me updated!

  [1]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/158

**Comment by vumanhcuongit** [comment] 2015-04-26 16:21
@gonzalo-bulnes 
I'm including ```Mongoid::Document``` in my model, a part of model is described below:
```ruby
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :first_name, type: String
  field :last_name, type: String

  # simple_token_authentication
  acts_as_token_authenticatable
  field :authentication_token, type: String
```
it's so weird :-?

**Comment by gonzalo-bulnes** [comment] 2015-04-26 16:32
Yes, its weird, just to be sure, can you try **v1.8.0**? You can do that this way:

**Downgrade _Simple Token Authentication_**

```ruby
# Gemfile

gem 'simple_token_authentication', '1.8.0'
```
Then `bundle update simple_token_authentication`.
You should get the same error, when launching your app, but if you don't then I may have committed a mistake in **v1.9.0**.


**Upgrade _Simple Token Authentication_ back**

```ruby
# Gemfile

gem 'simple_token_authentication', '~> 1.0'
```
Then `bundle update simple_token_authentication`.

**Comment by vumanhcuongit** [comment] 2015-04-26 16:35
@gonzalo-bulnes ya it works well in version **1.8.0**. I still don't know why, but thanks for your support :+1:

**Comment by gonzalo-bulnes** [comment] 2015-04-26 16:40
Ohohoh... bad news. It seems you caught a bug.

**Comment by gonzalo-bulnes** [comment] 2015-04-26 16:44
Can I ask you a favor? If you have a moment, could you please upgrade to **v1.9.0**, comment the `acts_as_token_authenticatable` call in your model and load the app? I would like to know if `acts_as_token_authentication_handler_for` method is missing too.

**Comment by vumanhcuongit** [comment] 2015-04-26 16:48
@gonzalo-bulnes I did it as you ask, but ```acts_as_token_authentication_handler_for``` is not missing.

**Comment by gonzalo-bulnes** [comment] 2015-04-26 18:08
Thanks!

**Comment by krsyoung** [comment] 2015-04-28 00:43
+1 here, let me know if I can help at all.

**Comment by gonzalo-bulnes** [comment] 2015-04-28 01:40
Hi @krsyoung, thank you for confirming the bug. You can review #165 if you want to help! I started reviewing e797557 without spotting my mistake.

**Comment by krsyoung** [comment] 2015-04-28 01:52
Will do @gonzalo-bulnes, reviewing #165.

**Comment by krsyoung** [comment] 2015-04-28 14:06
No dice.  I'm in need of some more research on the extend/include/inherit relationships.  Despite successfully extending `Mongoid::Document` the `User` model doesn't seem to pick up the `acts_as_token_authenticatable` function.

If I add `extend SimpleTokenAuthentication::ActsAsTokenAuthenticatable` to the `User` class everything works as expected.

Not sure if it might have something to do with `Mongoid::Document` which is included vs `ActiveRecord::Base` which is subclassed?

**Comment by gonzalo-bulnes** [comment] 2015-04-28 17:48
@krsyoung,

> Not sure if it might have something to do with Mongoid::Document which is included vs ActiveRecord::Base which is subclassed?

I was asking myself the same thing.

Indeed, **v1.9.0** added one level of indirection by defining the `TokenAuthenticatable` module. The `base class`es of all adapters but the `MongoidAdapter` are used through class inheritance, unlike the `Mongoid::Document` module. Since `acts_as_token_authenticatable` is a class method, that may well be causing the issue. (When you `include`a module in a class, its methods become instance methods; when you `extend` a class from the module, the module methods become class methods, when you inherit from a class, its instance methods become instance methods of the child class.)

If that were the cause of the issue, fixing it would be as easy as reverting the refactoring I did to extract the `TokenAuthenticatable` module. (That's to say: `git revert 15a4af7 dcfad63 e797557`.)

I'll take a closer look at this as soon as I can.

_Note: if you're looking for a book to read, the first chapter of [Metaprogramming Ruby 2][ref] by Paolo Perrotta does wonders explaining how modules take part in the methods lookup._
  [ref]: https://pragprog.com/book/ppmetr2/metaprogramming-ruby

**Comment by gonzalo-bulnes** [comment] 2015-04-28 23:42
Hi @krsyoung, @vumanhcuongit,

I confirm that @krsyoung was right, the issue was caused by the `MongoidAdapter` specificity which I didn't identify when refactoring `ActsAsTokenAuthenticatable`. Anyway, I added [the corresponding documentation][docs] and it should not happen again.

  [docs]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/b5b043c0cf3675c9825ce3d76ddcdc56f3e8061d/spec/lib/simple_token_authentication/acts_as_token_authenticatable_spec.rb#L110-L143

In order to cross-check the fix before releasing **v1.9.1**, I'd really appreciate if you could give a try to:

```ruby
# Gemfile

gem 'simple_token_authentication', git: 'git@github.com:gonzalo-bulnes/simple_token_authentication.git', branch: 'fix-broken-mongoid-adapter-expectation'
```

Regards!

**Comment by krsyoung** [comment] 2015-04-29 02:21
Hey @gonzalo-bulnes , I have much to learn from you :-)  I can confirm that things are working with the `fix-broken-mongoid-adapter-expectation` branch. 

Thanks for the quick response and expertise.  I'll also take your advice  on [Metaprogramming Ruby 2] (https://pragprog.com/book/ppmetr2/metaprogramming-ruby) so I can be a little more help next time around.

Thanks for all you do.

**Closed** 2015-04-29 02:52 UTC
Labels: bug

**Comment by gonzalo-bulnes** [comment] 2015-04-29 03:07
Here it is, **v1.9.1** ships the fix to this issue : )

@krsyoung (and @vumanhcuongit) there is nothing as valuable as peer review to make mistakes visible, many many thanks to both of us for your help!
