### ISSUE TITLE
Using multiple tokens for the same user to allow multiple devices to use the same API concurrently

### ISSUE THREAD

**Issue by aledalgrande** [gonzalo-bulnes/simple_token_authentication#317] opened 2017-10-20 05:42 UTC
It seems there was some talk about this in https://github.com/gonzalo-bulnes/simple_token_authentication/issues/21#issuecomment-36031740, but then there was silence.

Was anything implemented regarding this? A simple `has_many` that points to a table of tokens would fix it IMHO. On top of that, the tokens could be upgraded to have an expiry date.

Need a PR?

**Comment by karlingen** [comment] 2017-11-09 05:45
That would've been really nice. However, I think the maintainer for this project is under the radar. Last merged commit was almost a year ago. 

I planning on switching over to https://github.com/lynndylanhurley/devise_token_auth

It seems to have all of that good stuff

**Comment by aledalgrande** [comment] 2017-11-09 06:29
Yeah saw that, but I liked the simplicity of this one. I guess I'll have to switch sooner or later.

**Comment by karlingen** [comment] 2017-11-14 09:27
I've changed my mind. Don't do the switch to `devise_token_auth`. It is the must buggy gem I've ever worked with.

**Comment by aledalgrande** [comment] 2017-11-14 17:04
To do something this simple you shouldn't need a gem really. Just add a table and a warden strategy.

**Comment by gonzalo-bulnes** [comment] 2017-11-26 11:46
Hello @aledalgrande, @karlingen,

> <sarcasm: on>
Well, it seems the issue is resolved : )
Do you mind if I close it?
<sarcasm: off>
>
> -- probably myself if we knew each other and this wasn't a public forum

**Regarding [this comment][red]** and the corresponding reaction:

I'd like to remind here that the [code of conduct][coc] of this project mentions specifically the use of _derogatory comments_ as _unacceptable behaviour_.
As the maintainer of this project, I find both the comment and the following reaction quite dismissive and I would certainly qualify them as derogatory.

Besides that, I am not sure to be comfortable with the general tone of the conversation. The code of conduct contains examples of behavior that contributes to creating a positive environment. Please amend.

----

@aledalgrande Regarding having multiple tokens per user, the [FAQ][faq] tells me [that Tiddle may be a good alternative][tiddle] to Simple Token Authentication in the scenario you describe. I would take a look at it.

  [faq]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues?direction=desc&labels=question&page=1&sort=comments&state=closed
  [red]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/317#issuecomment-344196580
  [coc]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.15.1/CODE_OF_CONDUCT.md
  [tiddle]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/135#issuecomment-103938998

**Comment by aledalgrande** [comment] 2017-11-26 19:09
Amended, even if I don't fully agree... thanks for the tip on Tiddle.

**Comment by gonzalo-bulnes** [comment] 2017-11-27 06:01
Oh, I wasn't meaning to amend the comment, but the behaviour. Bad wording, sorry. You're welcome : )

**Closed** 2021-01-02 22:26 UTC
